# Generated by Django 4.2.4 on 2025-07-21 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('countries_visited', models.JSONField(default=list)),
                ('post_type', models.CharField(choices=[('jurnal', 'Jurnal'), ('recenzie', 'Recenzie'), ('itinerariu', 'Itinerariu'), ('sfaturi', 'Sfaturi & Ghiduri'), ('intrebari', 'Întrebări pentru Comunitate')], max_length=50)),
                ('travel_type', models.CharField(choices=[('solo', 'Solo'), ('family', 'Familie'), ('friends', 'Grup de Prieteni'), ('honeymoon', 'Luna de Miere'), ('business', 'Muncă'), ('guided_tour', 'Tur Ghidat'), ('couple', 'Cuplu'), ('backpacking', 'Backpacking')], max_length=50)),
                ('theme', models.CharField(choices=[('natura', 'Natură'), ('mare', 'Mare'), ('cultura', 'Cultură'), ('gastronomie', 'Gastronomie'), ('festival', 'Festival'), ('relaxare', 'Relaxare'), ('sport', 'Sport')], max_length=50)),
                ('travel_duration', models.CharField(blank=True, max_length=100)),
                ('images', models.JSONField(blank=True, default=list)),
                ('passport_count', models.IntegerField(default=0)),
                ('is_in_journal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='users.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
