# Generated by Django 4.2.4 on 2025-07-20 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_userprofile_postimage_comment_passportstamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='countries',
            new_name='countries_visited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='is_in_journal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='passport_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('journal', 'Jurnal'), ('review', 'Recenzie'), ('itinerary', 'Itinerariu'), ('tips_guides', 'Sfaturi & Ghiduri'), ('community_questions', 'Întrebări pentru Comunitate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('nature', 'Natură'), ('beach', 'Mare'), ('culture', 'Cultură'), ('gastronomy', 'Gastronomie'), ('festival', 'Festival'), ('relaxation', 'Relaxare'), ('sport', 'Sport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('family', 'Familie'), ('friends', 'Grup de Prieteni'), ('honeymoon', 'Luna de Miere'), ('business', 'Muncă'), ('guided_tour', 'Tur Ghidat'), ('couple', 'Cuplu'), ('backpacking', 'Backpacking')], max_length=50),
        ),
        migrations.DeleteModel(
            name='PassportStamp',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='postpassport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='users.post'),
        ),
        migrations.AddField(
            model_name='postpassport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postpassport',
            unique_together={('user', 'post')},
        ),
    ]
