# Generated by Django 4.2.4 on 2025-07-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_postpassport_remove_postimage_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('jurnal', 'Jurnal'), ('recenzie', 'Recenzie'), ('itinerariu', 'Itinerariu'), ('sfaturi', 'Sfaturi & Ghiduri'), ('intrebari', 'Întrebări pentru Comunitate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('natura', 'Natură'), ('mare', 'Mare'), ('cultura', 'Cultură'), ('gastronomie', 'Gastronomie'), ('festival', 'Festival'), ('relaxare', 'Relaxare'), ('sport', 'Sport')], max_length=50),
        ),
    ]
