# Generated by Django 5.1.1 on 2025-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_itinerary_itineraryday_itineraryactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='itinerary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
