# Generated by Django 4.2.4 on 2025-07-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_itinerary_itineraryday_itineraryactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryday',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='itineraryactivity',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itineraryactivity',
            name='description',
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='itinerary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('itinerary', 'date')},
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='day_number',
        ),
    ]
