# Generated by Django 5.1.1 on 2025-07-26 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryactivity',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='itineraryactivity',
            name='description',
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='day_number',
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('itinerary', 'date')},
        ),
        migrations.AlterModelOptions(
            name='itineraryday',
            options={'ordering': ['date']},
        ),
    ]
