# Generated by Django 5.1.1 on 2025-07-26 09:09

import datetime
from django.db import migrations


def populate_itinerary_dates(apps, schema_editor):
    """Populate date field for existing ItineraryDay records"""
    ItineraryDay = apps.get_model('users', 'ItineraryDay')
    
    # Group by itinerary to assign sequential dates
    itineraries = {}
    for day in ItineraryDay.objects.all().order_by('itinerary_id', 'id'):
        if day.itinerary_id not in itineraries:
            itineraries[day.itinerary_id] = datetime.date.today()
        
        day.date = itineraries[day.itinerary_id]
        day.save()
        
        # Increment date for next day in this itinerary
        itineraries[day.itinerary_id] += datetime.timedelta(days=1)


def reverse_populate_dates(apps, schema_editor):
    """Reverse operation - not needed for this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_itinerary_structure'),
    ]

    operations = [
        migrations.RunPython(populate_itinerary_dates, reverse_populate_dates),
    ]
