# Generated by Django 5.1.1 on 2025-07-26 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20250726_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
