
export const countries = {
  ro: [
    'RomÃ¢nia',
    'Germania',
    'FranÈ›a',
    'Italia',
    'Spania',
    'Portugalia',
    'Grecia',
    'Bulgaria',
    'Ungaria',
    'Austria',
    'ElveÈ›ia',
    'Olanda',
    'Belgia',
    'Luxemburg',
    'Republica CehÄƒ',
    'Slovacia',
    'Slovenia',
    'CroaÈ›ia',
    'Serbia',
    'Bosnia È™i HerÈ›egovina',
    'Muntenegru',
    'Macedonia de Nord',
    'Albania',
    'Ucraina',
    'Moldova',
    'Polonia',
    'Lituania',
    'Letonia',
    'Estonia',
    'Finlanda',
    'Suedia',
    'Norvegia',
    'Danemarca',
    'Islanda',
    'Irlanda',
    'Regatul Unit',
    'ScoÈ›ia',
    'Èšara Galilor',
    'Irlanda de Nord',
    'Anglia',
    'Malta',
    'Cipru',
    'Rusia',
    'Belarus',
    'Turcia',
    'Georgia',
    'Armenia',
    'Azerbaidjan',
    'Kazahstan',
    'Uzbekistan',
    'Turkmenistan',
    'KÃ¢rgÃ¢zstan',
    'Tadjikistan',
    'Mongolia',
    'China',
    'Japonia',
    'Coreea de Sud',
    'Coreea de Nord',
    'Taiwan',
    'Hong Kong',
    'Macao',
    'Filipine',
    'Indonesia',
    'Malaezia',
    'Singapore',
    'Brunei',
    'Thailanda',
    'Vietnam',
    'Laos',
    'Cambodgia',
    'Myanmar',
    'India',
    'Pakistan',
    'Bangladesh',
    'Sri Lanka',
    'Maldive',
    'Nepal',
    'Bhutan',
    'Afghanistan',
    'Iran',
    'Irak',
    'Siria',
    'Liban',
    'Iordania',
    'Israel',
    'Palestina',
    'Arabia SauditÄƒ',
    'Emiratele Arabe Unite',
    'Qatar',
    'Kuweit',
    'Bahrain',
    'Oman',
    'Yemen',
    'Egipt',
    'Libia',
    'Tunisia',
    'Algeria',
    'Maroc',
    'Sudan',
    'Sudanul de Sud',
    'Etiopia',
    'Eritreea',
    'Djibouti',
    'Somalia',
    'Kenya',
    'Uganda',
    'Tanzania',
    'Rwanda',
    'Burundi',
    'Republica DemocraticÄƒ Congo',
    'Republica Congo',
    'Republica CentrafricanÄƒ',
    'Ciad',
    'Camerun',
    'Nigeria',
    'Niger',
    'Mali',
    'Burkina Faso',
    'Senegal',
    'Mauritania',
    'Gambia',
    'Guinea-Bissau',
    'Guinea',
    'Sierra Leone',
    'Liberia',
    'Coasta de FildeÈ™',
    'Ghana',
    'Togo',
    'Benin',
    'Gabon',
    'Guinea EcuatorialÄƒ',
    'SÃ£o TomÃ© È™i PrÃ­ncipe',
    'Angola',
    'Zambia',
    'Malawi',
    'Mozambic',
    'Zimbabwe',
    'Botswana',
    'Namibia',
    'Africa de Sud',
    'Lesotho',
    'Eswatini',
    'Madagascar',
    'Mauritius',
    'Seychelles',
    'Comores',
    'Statele Unite',
    'Canada',
    'Mexic',
    'Guatemala',
    'Belize',
    'El Salvador',
    'Honduras',
    'Nicaragua',
    'Costa Rica',
    'Panama',
    'Cuba',
    'Jamaica',
    'Haiti',
    'Republica DominicanÄƒ',
    'Bahamas',
    'Barbados',
    'Trinidad È™i Tobago',
    'Grenada',
    'Saint Vincent È™i Grenadine',
    'Saint Lucia',
    'Dominica',
    'Antigua È™i Barbuda',
    'Saint Kitts È™i Nevis',
    'Brazilia',
    'Argentina',
    'Chile',
    'Peru',
    'Colombia',
    'Venezuela',
    'Ecuador',
    'Bolivia',
    'Paraguay',
    'Uruguay',
    'Guyana',
    'Suriname',
    'Guyana FrancezÄƒ',
    'Australia',
    'Noua ZeelandÄƒ',
    'Papua Noua Guinee',
    'Fiji',
    'Samoa',
    'Tonga',
    'Vanuatu',
    'Insulele Solomon',
    'Palau',
    'Micronezia',
    'Insulele Marshall',
    'Kiribati',
    'Nauru',
    'Tuvalu'
  ],
  en: [
    'Romania',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Portugal',
    'Greece',
    'Bulgaria',
    'Hungary',
    'Austria',
    'Switzerland',
    'Netherlands',
    'Belgium',
    'Luxembourg',
    'Czech Republic',
    'Slovakia',
    'Slovenia',
    'Croatia',
    'Serbia',
    'Bosnia and Herzegovina',
    'Montenegro',
    'North Macedonia',
    'Albania',
    'Ukraine',
    'Moldova',
    'Poland',
    'Lithuania',
    'Latvia',
    'Estonia',
    'Finland',
    'Sweden',
    'Norway',
    'Denmark',
    'Iceland',
    'Ireland',
    'United Kingdom',
    'Scotland',
    'Wales',
    'Northern Ireland',
    'England',
    'Malta',
    'Cyprus',
    'Russia',
    'Belarus',
    'Turkey',
    'Georgia',
    'Armenia',
    'Azerbaijan',
    'Kazakhstan',
    'Uzbekistan',
    'Turkmenistan',
    'Kyrgyzstan',
    'Tajikistan',
    'Mongolia',
    'China',
    'Japan',
    'South Korea',
    'North Korea',
    'Taiwan',
    'Hong Kong',
    'Macao',
    'Philippines',
    'Indonesia',
    'Malaysia',
    'Singapore',
    'Brunei',
    'Thailand',
    'Vietnam',
    'Laos',
    'Cambodia',
    'Myanmar',
    'India',
    'Pakistan',
    'Bangladesh',
    'Sri Lanka',
    'Maldives',
    'Nepal',
    'Bhutan',
    'Afghanistan',
    'Iran',
    'Iraq',
    'Syria',
    'Lebanon',
    'Jordan',
    'Israel',
    'Palestine',
    'Saudi Arabia',
    'United Arab Emirates',
    'Qatar',
    'Kuwait',
    'Bahrain',
    'Oman',
    'Yemen',
    'Egypt',
    'Libya',
    'Tunisia',
    'Algeria',
    'Morocco',
    'Sudan',
    'South Sudan',
    'Ethiopia',
    'Eritrea',
    'Djibouti',
    'Somalia',
    'Kenya',
    'Uganda',
    'Tanzania',
    'Rwanda',
    'Burundi',
    'Democratic Republic of Congo',
    'Republic of Congo',
    'Central African Republic',
    'Chad',
    'Cameroon',
    'Nigeria',
    'Niger',
    'Mali',
    'Burkina Faso',
    'Senegal',
    'Mauritania',
    'Gambia',
    'Guinea-Bissau',
    'Guinea',
    'Sierra Leone',
    'Liberia',
    'Ivory Coast',
    'Ghana',
    'Togo',
    'Benin',
    'Gabon',
    'Equatorial Guinea',
    'SÃ£o TomÃ© and PrÃ­ncipe',
    'Angola',
    'Zambia',
    'Malawi',
    'Mozambique',
    'Zimbabwe',
    'Botswana',
    'Namibia',
    'South Africa',
    'Lesotho',
    'Eswatini',
    'Madagascar',
    'Mauritius',
    'Seychelles',
    'Comoros',
    'United States',
    'Canada',
    'Mexico',
    'Guatemala',
    'Belize',
    'El Salvador',
    'Honduras',
    'Nicaragua',
    'Costa Rica',
    'Panama',
    'Cuba',
    'Jamaica',
    'Haiti',
    'Dominican Republic',
    'Bahamas',
    'Barbados',
    'Trinidad and Tobago',
    'Grenada',
    'Saint Vincent and the Grenadines',
    'Saint Lucia',
    'Dominica',
    'Antigua and Barbuda',
    'Saint Kitts and Nevis',
    'Brazil',
    'Argentina',
    'Chile',
    'Peru',
    'Colombia',
    'Venezuela',
    'Ecuador',
    'Bolivia',
    'Paraguay',
    'Uruguay',
    'Guyana',
    'Suriname',
    'French Guiana',
    'Australia',
    'New Zealand',
    'Papua New Guinea',
    'Fiji',
    'Samoa',
    'Tonga',
    'Vanuatu',
    'Solomon Islands',
    'Palau',
    'Micronesia',
    'Marshall Islands',
    'Kiribati',
    'Nauru',
    'Tuvalu'
  ]
};
export const searchCountries = (query, lang = 'ro') => {
  if (!query || query.length < 1) {
    return [];
  }
  const countryList = countries[lang] || countries.ro;
  const results = countryList.filter(country => 
    country.toLowerCase().includes(query.toLowerCase())
  ).slice(0, 10); 
  return results;
};
